INSERT INTO SUPPLIER (SUPPLIER_ID, APP_NO, CITY, HOUSE_NO, POST_CODE, STREET, DESCRIPTION)
	VALUES (1, 1, 'Szczecin', 1, '70-201', 'Street 1', 'Sup 01');
INSERT INTO SUPPLIER (SUPPLIER_ID, APP_NO, CITY, HOUSE_NO, POST_CODE, STREET, DESCRIPTION)
	VALUES (2, 2, 'Szczecin', 2, '70-202', 'Street 2', 'Sup 02');
INSERT INTO SUPPLIER (SUPPLIER_ID, APP_NO, CITY, HOUSE_NO, POST_CODE, STREET, DESCRIPTION)
	VALUES (3, 3, 'Szczecin', 3, '70-203', 'Street 3', 'Sup 03');
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (1, 'First product 11', 'Prod 11', 1, 3, 1);
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (2, 'Second product 21', 'Prod 21', 2, 3, 1);
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (3, 'Third product 31', 'Prod 31', 2, 3, 1);
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (4, 'First product 12', 'Prod 12', 1, 3, 2);
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (5, 'Second product 22', 'Prod 22', 2, 3, 2);
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (6, 'Third product 32', 'Prod 32', 2, 3, 2);
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (7, 'First product 13', 'Prod 13', 1, 3, 3);
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (8, 'Second product 23', 'Prod 23', 2, 3, 3);
INSERT INTO PRODUCT (PRODUCT_ID, DESCRIPTION, NAME, PRICE, QUANTITY, SUPPLIER_ID)
	VALUES (9, 'Third product 33', 'Prod 33', 2, 3, 3);